__recurse__ = False
__toc__ = [r'orb.core.backends.sql.mysql.statements.add_column_sql_mako',
r'orb.core.backends.sql.mysql.statements.alter_table_sql_mako',
r'orb.core.backends.sql.mysql.statements.create_index_sql_mako',
r'orb.core.backends.sql.mysql.statements.create_table_sql_mako',
r'orb.core.backends.sql.mysql.statements.create_view_sql_mako',
r'orb.core.backends.sql.mysql.statements.delete_sql_mako',
r'orb.core.backends.sql.mysql.statements.enable_internals_sql_mako',
r'orb.core.backends.sql.mysql.statements.insert_sql_mako',
r'orb.core.backends.sql.mysql.statements.quote_sql_mako',
r'orb.core.backends.sql.mysql.statements.schema_info_sql_mako',
r'orb.core.backends.sql.mysql.statements.select_aggregate_sql_mako',
r'orb.core.backends.sql.mysql.statements.select_count_sql_mako',
r'orb.core.backends.sql.mysql.statements.select_expand_sql_mako',
r'orb.core.backends.sql.mysql.statements.select_joiner_sql_mako',
r'orb.core.backends.sql.mysql.statements.select_shortcut_sql_mako',
r'orb.core.backends.sql.mysql.statements.select_sql_mako',
r'orb.core.backends.sql.mysql.statements.setup_db_sql_mako',
r'orb.core.backends.sql.mysql.statements.update_sql_mako',
r'orb.core.backends.sql.mysql.statements.where_sql_mako']